clone_options:
  path_to_source: jedi_bundle
  user_branch: ''
  github_orgs:
    - JCSDA-internal
    - JCSDA
    - GEOS-ESM
  bundles:
    - oops
    - ufo
  extra_repos: []
  crtm_tag_or_branch: v2.4.1-jedi.1

configure_options:
  platform: 'none'
  modules: 'none'
  cmake_build_type: release
  path_to_build: jedi_bundle/build
  custom_configure_options: ''
  external_modules: false

make_options:
  cores_to_use_for_make: 6
