clone_options:
  path_to_source: jedi_bundle
  user_branch: ''
  github_orgs:
    - JCSDA-internal
    - JCSDA
    - GEOS-ESM
  bundles:
    - oops

configure_options:
  platform: None
  modules: None
  cmake_build_type: release
  path_to_build: jedi_bundle/build
  custom_configure_options: ''

make_options:
  cores_to_use_for_make: 6
