build_options:

  platform: discover
  modules: intelclassic
  cmake_build_type: release
  path_to_build: &path_to_build ./
  cores_to_use_for_make: 6

source_code_options:

  pat_to_source: *path_to_build
  user_branch: develop
  github_orgs:
    - JCSDA-internal
    - JCSDA

  bundles:
    #- fv3-jedi
    #- soca
    - iodaconv
