clone_options:
  path_to_source: &code_path jedi_bundle
  user_branch: ''
  github_orgs:
    - JCSDA-internal
    - JCSDA
  bundles:
    - fv3-jedi
    - ioda
    - ufo

configure_options:
  platform: discover
  modules: intel
  cmake_build_type: release
  path_to_build: *code_path
  custom_configure_options: ''

make_options:
  cores_to_use_for_make: 6
