modules:
  default_modules: intel
  intel:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/jcsda/spack-stack/modulefiles
      - module load miniconda/3.9.7
      - module load ecflow/5.8.4
      - module use /gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2022.0.1/install/modulefiles/Core
      - module load stack-intel/2022.0.1
      - module load stack-intel-oneapi-mpi/2021.5.0
      - module load stack-python/3.9.7
      - module load jedi-ewok-env/1.0.0
      - module load jedi-fv3-env/1.0.0
      - module load nco/5.0.6
      - module load sp/2.3.3
    configure: -DMPIEXEC_EXECUTABLE="/usr/local/intel/oneapi/2021/mpi/2021.5.0/bin/mpirun" -DMPIEXEC_NUMPROC_FLAG="-np"
  gnu:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/jcsda/spack-stack/modulefiles
      - module load miniconda/3.9.7
      - module load ecflow/5.8.4
      - module use /discover/swdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-2.0.0-gnu-10.1.0/install/modulefiles/Core
      - module load stack-gcc/10.1.0
      - module load stack-openmpi/4.1.3
      - module load stack-python/3.9.7
      - module load jedi-ewok-env/1.0.0
      - module load jedi-fv3-env/1.0.0
      - module load nco/5.0.6
    configure: -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="-n"
