platform_name: noaa_hera
is_it_me:
  - command: 'hostname'
    contains: hfe
crtm_coeffs_path: '/scratch1/NCEPDEV/da/Cory.R.Martin/GDASApp/fix/crtm'
crtm_coeffs_version: '2.4.0'
modules:
  default_modules: intel
  intel:
    init:
      - source /apps/lmod/lmod/init/bash
    load:
      - module purge
      - module use /scratch1/NCEPDEV/jcsda/jedipara/spack-stack/modulefiles
      - module load miniconda/3.9.12
      - module load ecflow/5.5.3
      - module load mysql/8.0.31
      - module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core
      - module load stack-intel/2021.5.0
      - module load stack-intel-oneapi-mpi/2021.5.1
      - module load stack-python/3.10.8
      - module load jedi-fv3-env
      - module load soca-env
      - module load jedi-ufs-env/1.0.0
      - module unload gsibec crtm
    configure: -DMPIEXEC_EXECUTABLE="/usr/local/intel/oneapi/2021/mpi/2021.5.0/bin/mpirun" -DMPIEXEC_NUMPROC_FLAG="-np"
  gnu:
    init:
      - source /apps/lmod/lmod/init/bash
    load:
      - module purge
      - module use /scratch1/NCEPDEV/jcsda/jedipara/spack-stack/modulefiles
      - module load miniconda/3.9.12
      - module load ecflow/5.5.3
      - module load mysql/8.0.31
      - module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core
      - module load stack-gcc/9.2.0
      - module load stack-openmpi/4.1.5
      - module load stack-python/3.10.8
      - module load jedi-fv3-env
      - module load soca-env
      - module load jedi-ufs-env/1.0.0
      - module unload gsibec crtm
    configure: -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="-n"
