modules:
  default_modules: intel
  intel:
    load:
      - module purge
      - module use module use /work/noaa/da/jedipara/spack-stack/modulefiles
      - module load miniconda/3.9.7
      - module load ecflow/5.8.4
      - module use /work/noaa/da/role-da/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.2/install/modulefiles/Core
      - module load stack-intel/2022.0.2
      - module load stack-intel-oneapi-mpi/2021.5.1
      - module load stack-python/3.9.7
      - module load jedi-fv3-env/1.0.0
      - module load jedi-ewok-env/1.0.0
      - module load nco/5.0.6
    configure: -DMPIEXEC_EXECUTABLE=/opt/slurm/bin/srun -DMPIEXEC_NUMPROC_FLAG="-n"
  gnu:
    load:
      - module purge
      - module use module use /work/noaa/da/jedipara/spack-stack/modulefiles
      - module load miniconda/3.9.7
      - module load ecflow/5.8.4
      - module use /work/noaa/da/role-da/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.2.0-openmpi-4.0.4/install/modulefiles/Core
      - module load stack-gcc/10.2.0
      - module load stack-openmpi/4.0.4
      - module load stack-python/3.9.7
      - module load jedi-fv3-env/1.0.0
      - module load jedi-ewok-env/1.0.0
      - module load nco/5.0.6
    configure: -DMPIEXEC_EXECUTABLE=/opt/slurm/bin/srun -DMPIEXEC_NUMPROC_FLAG="-n"
