# Jedi cmake
- jedicmake:
    repo_url_name: jedi-cmake
    default_branch: develop
    cmakelists: 'include( jedicmake/cmake/Functions/git_functions.cmake )'
    recursive: true
    tag: False

# Oops
- oops:
    default_branch: develop

# Background error models
- gsibec:
    repo_url_name: GSIbec
    default_branch: 1.1.2
    tag: true
- saber:
    default_branch: develop

# Observation operators
- ioda-data:
    default_branch: develop
- ioda:
    default_branch: develop
- iodaconv:
    repo_url_name: ioda-converters
    default_branch: develop
- geos-aero:
    default_branch: develop
- gsw:
    repo_url_name: GSW-Fortran
    default_branch: develop
- ropp-ufo:
    default_branch: develop
    repo_url_name: ropp-test
- rttov:
    default_branch: develop
- crtm:
    default_branch: v2.4-jedi.2
    repo_url_name: crtm
    tag: true
- ufo-data:
    default_branch: develop
- ufo:
    default_branch: develop

# Variable changes
- vader:
    default_branch: develop

# Soca and fv3
- fms:
    repo_url_name: FMS
    default_branch: release-stable

# Soca
- icepack:
    repo_url_name: Icepack
    default_branch: feature/ecbuild-new
- mom6:
    repo_url_name: MOM6
    default_branch: main-ecbuild
- soca:
    default_branch: develop

# Fv3-jedi
- fv3:
    repo_url_name: GFDL_atmos_cubed_sphere
    default_branch: release-stable
- fv3-jedi-lm:
    repo_url_name: fv3-jedi-linearmodel
    default_branch: develop
- femps:
    default_branch: develop
- fv3-jedi-data:
    default_branch: develop
- fv3-jedi:
    default_branch: develop
