optional_repos:
  - ropp-ufo
  - geos-aero

required_repos:
  - jedicmake
  - oops
  - gsibec
  - saber
  - ioda
  - ufo
  - vader
  - fms
  - fv3
  - fv3-jedi-lm
  - femps
  - fv3-jedi
  - ioda-data
  - fv3-jedi-data
