name: JEDI Bundle Pinned Version Test

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  buildbundle:
    name: Run jedi_bundle with pinned_versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.12"]

    steps:

    # Setup Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Update conda
    #- name: Update conda
    #  run: conda update -n base -c defaults conda

    # Install pip
    #- name: Install pip
    #  run: conda install pip

    # Clone the code repo
    - name: Clone code repo
      uses: actions/checkout@v4
      with:
        lfs: true

    # Install package
    #- name: Upgrade pip
    #  run: $CONDA/bin/pip3 install --upgrade pip
    #- name: Install JEDI bundle and dependencies
    #  run: $CONDA/bin/pip3 install --use-deprecated=legacy-resolver -r requirements.txt --user .

    - name: Install JEDI bundle and dependencies
      run: python -m pip install --use-deprecated=legacy-resolver -r requirements.txt --user .
    - name: Put executables in the path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Run an application test
    - name: Run JEDI Bundle application test
      run: jedi_bundle -pv

    # Confirm existence of expected file
    - name: Check
      run: ls -l build.yaml
